import { getDB, guardarDB } from './db.js';
import { mostrarNotificacion } from './utils.js';

export function mostrarModalAgregarCliente(callback) {
    document.getElementById('root').innerHTML = `<div class="modal"><div class="modal-content w-full max-w-md"><h2 class="text-xl font-bold mb-4">👤 Agregar Cliente</h2>
        <div class="space-y-3"><input type="text" id="nombre" placeholder="Nombre *" class="w-full p-3 border border-gray-200 dark:border-gray-700 rounded-xl"><input type="text" id="cuit" placeholder="CUIT" class="w-full p-3 border rounded-xl"><input type="text" id="telefono" placeholder="Teléfono" class="w-full p-3 border rounded-xl"><input type="email" id="email" placeholder="Email" class="w-full p-3 border rounded-xl"><input type="text" id="direccion" placeholder="Dirección" class="w-full p-3 border rounded-xl"><input type="text" id="contacto" placeholder="Contacto" class="w-full p-3 border rounded-xl"><input type="text" id="whatsapp" placeholder="WhatsApp" class="w-full p-3 border rounded-xl"><input type="text" id="cbu" placeholder="CBU" class="w-full p-3 border rounded-xl"><input type="number" id="diasCobro" placeholder="Días cobro" value="30" class="w-full p-3 border rounded-xl"></div>
        <div class="flex gap-3 mt-5"><button id="guardarBtn" class="flex-1 bg-green-600 text-white py-3 rounded-xl">Guardar</button><button id="cancelarBtn" class="flex-1 bg-gray-300 dark:bg-gray-700 py-3 rounded-xl">Cancelar</button></div></div></div>`;
    document.getElementById('guardarBtn').onclick = () => { const nombre = document.getElementById('nombre').value; if (nombre) callback({ nombre, cuit: document.getElementById('cuit').value, telefono: document.getElementById('telefono').value, email: document.getElementById('email').value, direccion: document.getElementById('direccion').value, contacto: document.getElementById('contacto').value, whatsapp: document.getElementById('whatsapp').value, cbu: document.getElementById('cbu').value, diasCobro: parseInt(document.getElementById('diasCobro').value) || 30 }); else mostrarNotificacion("Nombre requerido", 'error'); };
    document.getElementById('cancelarBtn').onclick = () => window.dispatchEvent(new Event('closeModal'));
}

export function mostrarModalAgregarProveedor(callback) {
    document.getElementById('root').innerHTML = `<div class="modal"><div class="modal-content w-full max-w-md"><h2 class="text-xl font-bold mb-4">🏭 Agregar Proveedor</h2>
        <div class="space-y-3"><input type="text" id="nombre" placeholder="Nombre *" class="w-full p-3 border rounded-xl"><input type="text" id="cuit" placeholder="CUIT" class="w-full p-3 border rounded-xl"><input type="text" id="telefono" placeholder="Teléfono" class="w-full p-3 border rounded-xl"><input type="email" id="email" placeholder="Email" class="w-full p-3 border rounded-xl"><input type="text" id="direccion" placeholder="Dirección" class="w-full p-3 border rounded-xl"><input type="text" id="contacto" placeholder="Contacto" class="w-full p-3 border rounded-xl"><input type="text" id="cbu" placeholder="CBU" class="w-full p-3 border rounded-xl"><input type="text" id="rubro" placeholder="Rubro" class="w-full p-3 border rounded-xl"><input type="number" id="diasPago" placeholder="Días pago" value="30" class="w-full p-3 border rounded-xl"></div>
        <div class="flex gap-3 mt-5"><button id="guardarBtn" class="flex-1 bg-green-600 text-white py-3 rounded-xl">Guardar</button><button id="cancelarBtn" class="flex-1 bg-gray-300 dark:bg-gray-700 py-3 rounded-xl">Cancelar</button></div></div></div>`;
    document.getElementById('guardarBtn').onclick = () => { const nombre = document.getElementById('nombre').value; if (nombre) callback({ nombre, cuit: document.getElementById('cuit').value, telefono: document.getElementById('telefono').value, email: document.getElementById('email').value, direccion: document.getElementById('direccion').value, contacto: document.getElementById('contacto').value, cbu: document.getElementById('cbu').value, rubro: document.getElementById('rubro').value, diasPago: parseInt(document.getElementById('diasPago').value) || 30 }); else mostrarNotificacion("Nombre requerido", 'error'); };
    document.getElementById('cancelarBtn').onclick = () => window.dispatchEvent(new Event('closeModal'));
}

export function mostrarModalAgregarCostoFijo(callback) {
    const db = getDB();
    document.getElementById('root').innerHTML = `<div class="modal"><div class="modal-content w-full max-w-md"><h2 class="text-xl font-bold mb-4">💰 Agregar Costo Fijo</h2>
        <div class="space-y-3"><input type="text" id="nombre" placeholder="Nombre" class="w-full p-3 border rounded-xl"><input type="number" id="monto" placeholder="Monto" class="w-full p-3 border rounded-xl"><input type="date" id="vencimiento" class="w-full p-3 border rounded-xl"><select id="categoria" class="w-full p-3 border rounded-xl">${db.categoriasGastos.map(c => `<option value="${c}">${c}</option>`).join('')}</select><label class="flex items-center gap-2"><input type="checkbox" id="recurrente"> Recurrente (mensual)</label></div>
        <div class="flex gap-3 mt-5"><button id="guardarBtn" class="flex-1 bg-green-600 text-white py-3 rounded-xl">Guardar</button><button id="cancelarBtn" class="flex-1 bg-gray-300 dark:bg-gray-700 py-3 rounded-xl">Cancelar</button></div></div></div>`;
    document.getElementById('guardarBtn').onclick = () => { const nombre = document.getElementById('nombre').value; const monto = parseFloat(document.getElementById('monto').value); if (nombre && !isNaN(monto)) callback({ nombre, monto, vencimiento: document.getElementById('vencimiento').value, categoria: document.getElementById('categoria').value, recurrente: document.getElementById('recurrente').checked }); else mostrarNotificacion("Complete los datos", 'error'); };
    document.getElementById('cancelarBtn').onclick = () => window.dispatchEvent(new Event('closeModal'));
}
